### ISSUE TITLE
Bug :: Method not found: 'System.String System.String.Clone()'

### ISSUE THREAD

**Issue by YODevs** [YODevs/YO#109]
```f#
func clone(val:str)
{
 let myobj : obj = val::clone()
 System.Console::WriteLine(myobj)
}
```

error : 
```
Unhandled Exception: System.MissingMethodException: Method not found: 'System.String System.String.Clone()'.
   at string_test.clone(String val)
   at string_test.main()
```

**Comment by YODevs** [comment]
Fixed .
